### ISSUE TITLE
[3주차] Optional과 Date/Time

### ISSUE THREAD

**Issue by gowoonsori** [Nelmm/Java8#6]
# 공부할 내용
- [x] Optional  소개
- [x] Optional  API
- [x] Date와 Time
- [x] Date/Time API

**Comment by gowoonsori** [comment]
## truncatedTo() : Month, Year은 못 오는 이유
- truncated는 생략,잘림이라는 뜻.
- 영준님이 말씀하신 것처럼 일수부터는 생략한다는 개념이 모호함 
- day에 0이 오는것도 말이 안되며 1이 온다고 해도 일수를 잘라내 정확히 년,월을 뜻하는게 아니라 년,월,1일을 뜻하는 것이기 때문에

### 하지만 해당해의 1일을 만약에 표시하고 싶을경우 : TemporalAdjusters(시간 조정기)를 이용할 수 있다.
- date.with(TemporalAdjusters.firstDayOfMonth()).truncatedTo(ChronoUnit.DAYS);   //2021-11-01T00:00
- date.with(TemporalAdjusters.firstDayOfYear()) : 해당 년도의 1월 1일          //2021-01-01T17:02:22.973160900
- date.with(TemporalAdjusters.firstDayOfMonth()) : 해당 월의 1일               //2021-11-01T17:03:05.777745100
- date.with(TemporalAdjusters.lastDayOfYear()) : 해당 년도의 마지막 날짜  //2021-12-31T17:03:34.531656400
- date.with(TemporalAdjusters.lastDayOfMonth()) : 해당 월의 마지막 날짜 //2021-11-30T17:04:03.837483400

**Comment by ventulus95** [comment]
귀찮아서 PR 내가 합침 문제 없을듯 ㅋㅋ
